name: diffusion
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.1=hd590300_1
  - pip=23.1.2=pyhd8ed1ab_0
  - python=3.8.16=he550d4f_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.19.0
    - aggdraw==1.3.16
    - aiofiles==23.2.1
    - aiohttp==3.9.0
    - aiosignal==1.3.1
    - aiostream==0.5.2
    - alembic==1.13.1
    - aniso8601==9.0.1
    - annotated-types==0.6.0
    - anyio==3.7.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bcrypt==4.0.1
    - beartype==0.17.2
    - beautifulsoup4==4.12.3
    - blinker==1.7.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.16.0
    - cfgv==3.4.0
    - charset-normalizer==2.1.1
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.26.3
    - colorama==0.4.6
    - colossalai==0.3.5
    - contexttimer==0.3.3
    - contourpy==1.0.7
    - cryptography==41.0.5
    - cycler==0.11.0
    - dearpygui==1.9.1
    - decorator==5.1.1
    - deprecated==1.2.14
    - dicomweb-client==0.59.1
    - diffusers==0.16.1
    - diskcache==5.6.3
    - distlib==0.3.8
    - docarray==0.39.1
    - docker==6.1.3
    - docker-pycreds==0.4.0
    - ecdsa==0.18.0
    - einops==0.7.0
    - einops-exts==0.0.4
    - entrypoints==0.4
    - exceptiongroup==1.1.3
    - expiring-dict==1.1.0
    - expiringdict==1.2.2
    - fabric==3.2.2
    - fastapi==0.95.0
    - filelock==3.11.0
    - fire==0.5.0
    - flask==3.0.2
    - fonttools==4.39.4
    - frozenlist==1.4.0
    - fsspec==2023.4.0
    - fvcore==0.1.5.post20221221
    - gdown==5.1.0
    - generative==0.0.0
    - geomloss==0.2.6
    - girder-client==3.1.17
    - gitdb==4.0.11
    - gitpython==3.1.42
    - google==3.0.0
    - google-auth==2.19.1
    - google-auth-oauthlib==1.0.0
    - graphene==3.3
    - graphql-core==3.2.3
    - graphql-relay==3.2.0
    - greenlet==3.0.3
    - grpcio==1.54.2
    - grpcio-health-checking==1.48.2
    - grpcio-reflection==1.48.2
    - gunicorn==21.2.0
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==0.16.3
    - httptools==0.6.1
    - httpx==0.23.3
    - huggingface-hub==0.15.1
    - humanize==4.8.0
    - identify==2.5.34
    - idna==3.4
    - imageio==2.31.0
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - invoke==2.2.0
    - iopath==0.1.10
    - itk==5.3.0
    - itk-core==5.3.0
    - itk-filtering==5.3.0
    - itk-io==5.3.0
    - itk-numerics==5.3.0
    - itk-registration==5.3.0
    - itk-segmentation==5.3.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==3.2.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.4
    - kornia==0.7.1
    - lazy-loader==0.3
    - lightning-utilities==0.10.1
    - lit==16.0.5.post0
    - lmdb==1.4.1
    - lpips==0.1.4
    - lz4==3.1.1
    - mako==1.3.2
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mlflow==2.11.1
    - monai==1.2.0
    - monai-generative==0.2.2
    - monailabel==0.7.0rc5
    - mpmath==1.2.1
    - msgpack==1.0.7
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - networkx==3.0rc1
    - nibabel==5.1.0
    - ninja==1.11.1
    - nodeenv==1.8.0
    - nptyping==2.5.0
    - numpy==1.24.1
    - numpymaxflow==0.0.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - openslide-python==1.1.2
    - orjson==3.9.10
    - packaging==23.1
    - pandas==2.0.2
    - paramiko==3.4.0
    - passlib==1.7.4
    - pathspec==0.11.2
    - pillow==9.3.0
    - piqa==1.3.2
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.0
    - portalocker==2.8.2
    - pre-commit==3.5.0
    - prometheus-client==0.19.0
    - protobuf==3.20.1
    - psutil==5.9.5
    - pyarrow==15.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydantic==1.10.14
    - pydantic-core==2.14.3
    - pydicom==2.3.1
    - pydicom-seg==0.4.1
    - pygments==2.15.1
    - pymcubes==0.1.4
    - pynacl==1.5.0
    - pynetdicom==2.0.2
    - pynrrd==1.0.0
    - pyparsing==3.0.9
    - pyrsistent==0.20.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-jose==3.3.0
    - python-multipart==0.0.6
    - pytorch-ignite==0.4.11
    - pytorch-triton==2.1.0+9820899b38
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - ray==2.9.2
    - referencing==0.33.0
    - regex==2023.6.3
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.10.1
    - retrying==1.3.4
    - rfc3986==1.5.0
    - rich==13.4.1
    - rotary-embedding-torch==0.5.3
    - rpds-py==0.18.0
    - rsa==4.9
    - safetensors==0.4.2
    - schedule==1.1.0
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentencepiece==0.1.99
    - sentry-sdk==1.40.4
    - setproctitle==1.3.3
    - shapely==2.0.1
    - shellingham==1.5.3
    - simpleitk==2.2.1
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.5
    - sqlalchemy==2.0.28
    - sqlparse==0.4.4
    - starlette==0.26.1
    - sympy==1.11.1
    - tabulate==0.9.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - tensorboardx==2.6
    - termcolor==2.4.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2023.7.10
    - timeloop==1.0.2
    - timm==0.9.12
    - tokenizers==0.13.3
    - torch==2.0.1
    - torch-ema==0.3
    - torchaudio==2.0.2
    - torchio==0.19.1
    - torchmetrics==1.3.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - transformers==4.29.2
    - trimesh==3.21.7
    - triton==2.0.0
    - typer==0.9.0
    - types-requests==2.31.0.6
    - types-urllib3==1.26.25.14
    - typing-extensions==4.8.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - urllib3==1.26.13
    - uvicorn==0.21.1
    - uvloop==0.19.0
    - virtualenv==20.25.0
    - visualkeras==0.0.2
    - wandb==0.16.3
    - watchdog==3.0.0
    - watchfiles==0.21.0
    - websocket-client==1.6.4
    - websockets==12.0
    - werkzeug==3.0.1
    - wrapt==1.15.0
    - xatlas==0.0.7
    - yacs==0.1.8
    - yarl==1.9.3
    - zipp==3.15.0
